"""empty message

Revision ID: 1249c22e2378
Revises: 882ea16366b2
Create Date: 2016-11-02 21:51:27.249977

"""

# revision identifiers, used by Alembic.
revision = '1249c22e2378'
down_revision = '882ea16366b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('from_userid', sa.Integer(), nullable=False),
    sa.Column('to_userid', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_userid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Removed 'u' prefix from string literal as it's no longer needed in SQLAlchemy 2.1
    op.add_column('user', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed 'u' prefix from string literal as it's no longer needed in SQLAlchemy 2.1
    op.drop_column('user', 'email_confirmed')
    op.drop_table('message')
    # ### end Alembic commands ###