"""empty message

Revision ID: 4e928c9d9511
Revises: 1249c22e2378
Create Date: 2016-11-12 10:04:49.279885

"""

# revision identifiers, used by Alembic.
revision = '4e928c9d9511'
down_revision = '1249c22e2378'
# Added branch_labels and depends_on parameters for SQLAlchemy 2.x Alembic compatibility
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # Commands auto generated by Alembic - please adjust!
    op.add_column('user', sa.Column('auth_linkedin', sa.String(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'salt',
               existing_type=sa.VARCHAR(),
               nullable=True)


def downgrade():
    # Commands auto generated by Alembic - please adjust!
    op.alter_column('user', 'salt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'auth_linkedin')