"""empty message

Revision ID: 6f19087c1e9d
Revises: b0050cb92b95
Create Date: 2016-11-19 13:03:06.429349

"""

# revision identifiers, used by Alembic.
revision = '6f19087c1e9d'
down_revision = 'b0050cb92b95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('misc_info', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'misc_info')
    ### end Alembic commands ###
