"""empty message

Revision ID: 70a639c53ae5
Revises: 06b52c05a349
Create Date: 2016-10-23 10:48:07.041946

"""

# revision identifiers, used by Alembic.
revision = '70a639c53ae5'
down_revision = '06b52c05a349'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('category', sa.String(), nullable=False))
    op.add_column('listing', sa.Column('cover_image_url', sa.String(), nullable=True))
    op.add_column('listing', sa.Column('product_icon_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_listing_category'), 'listing', ['category'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_category'), table_name='listing')
    op.drop_column('listing', 'product_icon_url')
    op.drop_column('listing', 'cover_image_url')
    op.drop_column('listing', 'category')
    ### end Alembic commands ###
