"""empty message

Revision ID: 882ea16366b2
Revises: 70a639c53ae5
Create Date: 2016-10-29 16:04:31.268632

"""

# revision identifiers, used by Alembic.
revision = '882ea16366b2'
down_revision = '70a639c53ae5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('slug', sa.String(), nullable=False, server_default='default'))
    op.alter_column('listing', 'slug', server_default=None)
    op.add_column('listing', sa.Column('total_customers', sa.Integer(), nullable=True))
    op.create_index('ix_listing_slug', 'listing', ['slug'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listing_slug', table_name='listing')
    op.drop_column('listing', 'total_customers')
    op.drop_column('listing', 'slug')
    ### end Alembic commands ###
