"""empty message

Revision ID: b0050cb92b95
Revises: 4e928c9d9511
Create Date: 2016-11-13 11:29:56.222984

"""

# revision identifiers, used by Alembic.
revision = 'b0050cb92b95'
down_revision = '4e928c9d9511'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('iot', sa.Boolean(), nullable=True))
    op.add_column('listing', sa.Column('robotics', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'robotics')
    op.drop_column('listing', 'iot')
    ### end Alembic commands ###
