#
# listing.py
#
#
from sqlalchemy import orm
from main import db
from base import Base


class Listing(Base):
    __tablename__ = 'listing'

    # who's doing the listing
    userid = db.Column(db.ForeignKey('user.id'), nullable=False)

    #
    status = db.Column(db.String)     # draft|published

    # info
    name = db.Column(db.String, nullable=False, index=True)
    domain = db.Column(db.String, nullable=False, index=True)
    category = db.Column(db.String, nullable=False, index=True)
    slug = db.Column(db.String, nullable=False, index=True) # autogenerated

    app_ios = db.Column(db.Boolean, default=False)
    app_android = db.Column(db.Boolean, default=False)
    web_app = db.Column(db.Boolean, default=False)
    iot = db.Column(db.Boolean, default=False)
    robotics = db.Column(db.Boolean, default=False)

    # images
    cover_image_url = db.Column(db.String)
    product_icon_url = db.Column(db.String)
    # other images are stored as ListingImage in image schema

    incorporated = db.Column(db.Boolean, default=False)
    employees = db.Column(db.Integer)

    product_info = db.Column(db.Text)
    tech_stack = db.Column(db.Text)
    founder_info = db.Column(db.Text)

    # busienss metrics
    launch_date = db.Column(db.DateTime)      # day it was launched
    mau = db.Column(db.Integer)               # monthly active users
    revenue_cents = db.Column(db.Integer)     # monthly revenue in cents
    investment_cents = db.Column(db.Integer)  # total investment
    total_customers = db.Column(db.Integer)   # size of customer base
    misc_info = db.Column(db.Text)            # additional info

    # links
    linkedin = db.Column(db.String)
    angellist = db.Column(db.String)
    crunchbase = db.Column(db.String)

    # Changed from backref to back_populates as backref is deprecated in SQLAlchemy 2.0+
    user = orm.relationship('User', back_populates='listings')

    @property
    def cover_image(self):
        return self.cover_image_url or '/static/images/bg.jpg'

    @property
    def product_icon(self):
        return self.product_icon_url or '/static/images/avatar.jpg'

    @classmethod
    def filter_like_name(cls, name, asmatch=False):
        if asmatch:
            # Changed from match() to text search function using ilike() which is more compatible in SQLAlchemy 2.x
            return cls.name.ilike(f'%{name}%')
        # Updated string formatting to use f-strings
        return cls.name.ilike(f'%{name}%')

    @classmethod
    def filter_like_domain(cls, domain, asmatch=False):
        if asmatch:
            # Fixed variable name typo (name -> domain) and updated to ilike()
            return cls.domain.ilike(f'%{domain}%')
        # Updated string formatting to use f-strings
        return cls.domain.ilike(f'%{domain}%')

    @classmethod
    def filter_like_category(cls, category, asmatch=False):
        if asmatch:
            # Updated from match() to ilike() 
            return cls.category.ilike(f'%{category}%')
        # Updated string formatting to use f-strings
        return cls.category.ilike(f'%{category}%')